{{- $top := . -}}
{{- range $secrets := .Values.secrets -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Values.referenceId }}.es.{{ $secrets.secretKey }}
spec:
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: {{ $secrets.secretName }}
  data:
    - secretKey: {{ $secrets.secretKey }}
      remoteRef:
        key: {{ $secrets.remoteSecretKey }}
        version: {{ $secrets.remoteSecretVersion | quote }}
{{ end }}